export enum QueryKeys {
  messages = 'messages',
  sharedMessages = 'sharedMessages',
  sharedLinks = 'sharedLinks',
  allConversations = 'allConversations',
  archivedConversations = 'archivedConversations',
  searchConversations = 'searchConversations',
  conversation = 'conversation',
  searchEnabled = 'searchEnabled',
  user = 'user',
  name = 'name', // user key name
  models = 'models',
  balance = 'balance',
  endpoints = 'endpoints',
  presets = 'presets',
  searchResults = 'searchResults',
  tokenCount = 'tokenCount',
  availablePlugins = 'availablePlugins',
  startupConfig = 'startupConfig',
  assistants = 'assistants',
  assistant = 'assistant',
  agents = 'agents',
  agent = 'agent',
  files = 'files',
  fileConfig = 'fileConfig',
  tools = 'tools',
  toolAuth = 'toolAuth',
  toolCalls = 'toolCalls',
  mcpTools = 'mcpTools',
  mcpConnectionStatus = 'mcpConnectionStatus',
  mcpAuthValues = 'mcpAuthValues',
  agentTools = 'agentTools',
  actions = 'actions',
  assistantDocs = 'assistantDocs',
  agentDocs = 'agentDocs',
  fileDownload = 'fileDownload',
  voices = 'voices',
  customConfigSpeech = 'customConfigSpeech',
  prompts = 'prompts',
  prompt = 'prompt',
  promptGroups = 'promptGroups',
  allPromptGroups = 'allPromptGroups',
  promptGroup = 'promptGroup',
  categories = 'categories',
  randomPrompts = 'randomPrompts',
  agentCategories = 'agentCategories',
  marketplaceAgents = 'marketplaceAgents',
  roles = 'roles',
  conversationTags = 'conversationTags',
  health = 'health',
  userTerms = 'userTerms',
  banner = 'banner',
  /* Memories */
  memories = 'memories',
  principalSearch = 'principalSearch',
  accessRoles = 'accessRoles',
  resourcePermissions = 'resourcePermissions',
  effectivePermissions = 'effectivePermissions',
  graphToken = 'graphToken',
  /* MCP Servers */
  mcpServers = 'mcpServers',
  mcpServer = 'mcpServer',
  /* Active Jobs */
  activeJobs = 'activeJobs',
  /* Charts */
  charts = 'charts',
  chart = 'chart',
  chartData = 'chartData',
  /* Dashboards */
  dashboards = 'dashboards',
  dashboard = 'dashboard',
  dashboardFull = 'dashboardFull',
  sharedDashboards = 'sharedDashboards',
  publicDashboard = 'publicDashboard',
  /* Subscriptions */
  subscription = 'subscription',
  subscriptionHistory = 'subscriptionHistory',
  subscriptionPlans = 'subscriptionPlans',
  subscriptionUsage = 'subscriptionUsage',
  subscriptionInvoices = 'subscriptionInvoices',
  /* Saved Queries */
  savedQueries = 'savedQueries',
  savedQuery = 'savedQuery',
}

// Dynamic query keys that require parameters
export const DynamicQueryKeys = {
  agentFiles: (agentId: string) => ['agentFiles', agentId] as const,
} as const;

export enum MutationKeys {
  createChart = 'createChart',
  updateChart = 'updateChart',
  deleteChart = 'deleteChart',
  duplicateChart = 'duplicateChart',
  createDashboard = 'createDashboard',
  updateDashboard = 'updateDashboard',
  deleteDashboard = 'deleteDashboard',
  duplicateDashboard = 'duplicateDashboard',
  updateDashboardLayout = 'updateDashboardLayout',
  addChartToDashboard = 'addChartToDashboard',
  removeChartFromDashboard = 'removeChartFromDashboard',
  toggleDashboardStar = 'toggleDashboardStar',
  createCheckout = 'createCheckout',
  cancelSubscription = 'cancelSubscription',
  resumeSubscription = 'resumeSubscription',
  changePlan = 'changePlan',
  fileUpload = 'fileUpload',
  fileDelete = 'fileDelete',
  updatePreset = 'updatePreset',
  deletePreset = 'deletePreset',
  loginUser = 'loginUser',
  logoutUser = 'logoutUser',
  refreshToken = 'refreshToken',
  avatarUpload = 'avatarUpload',
  speechToText = 'speechToText',
  textToSpeech = 'textToSpeech',
  assistantAvatarUpload = 'assistantAvatarUpload',
  agentAvatarUpload = 'agentAvatarUpload',
  updateAction = 'updateAction',
  updateAgentAction = 'updateAgentAction',
  deleteAction = 'deleteAction',
  deleteAgentAction = 'deleteAgentAction',
  revertAgentVersion = 'revertAgentVersion',
  deleteUser = 'deleteUser',
  updateRole = 'updateRole',
  enableTwoFactor = 'enableTwoFactor',
  verifyTwoFactor = 'verifyTwoFactor',
  updateMemoryPreferences = 'updateMemoryPreferences',
  createSavedQuery = 'createSavedQuery',
  updateSavedQuery = 'updateSavedQuery',
  deleteSavedQuery = 'deleteSavedQuery',
}
